add kill and wait

diff --git a/.github/workflows/build-module.yml b/.github/workflows/build-module.yml
--- a/.github/workflows/build-module.yml
+++ b/.github/workflows/build-module.yml
@@ -116,8 +116,16 @@ jobs:
         name: ${{ inputs.ArtifactSource || inputs.CacheSource }}-${{ inputs.module }}
         path: qt6.tar.xz
     - run: |
-        pid="$(pgrep ninja)"
-        [[ "$pid" != "" ]] && kill -SIGINT "$pid" && lsof -p "$pid" +r 1 | awk '/^=/ { if (T++ >= 120) { exit 1 } }' || :
+        kill_and_wait () {
+          pids="$(pgrep "$1")"
+          echo "Found the following $1 instances"
+          while read -r pid; do
+            echo "send sigint to $pid"
+            kill -SIGINT "$pid" && lsof -p "$pid" +r 1 | awk '/^=/ { if (T++ >= 120) { exit 1 } }' && echo "$pid has exited" || echo "Failed to kill or wait for $pid"
+          done <<< "$pids"
+        }
+        kill_and_wait make
+        kill_and_wait ninja
       if: ${{ !(steps.build1.outcome == 'success' || steps.build2.outcome == 'success') }}
     - uses: actions/github-script@v4
       with:
